common:
  - cache_plugin: &cache
      cache#v0.6.0:
        manifest: pnpm-lock.yaml
        path: node_modules
        restore: file

steps:
  - label: ':package: Install Node Modules'
    key: 'install'
    commands:
      - pnpm install
    agents:
      queue: default
    plugins:
      - cache#v0.6.0:
          manifest: pnpm-lock.yaml
          path: node_modules
          restore: pipeline
          save: file

  - label: ':rotating_light: Lint'
    depends_on: 'install'
    commands:
      - pnpm lint
    agents:
      queue: default
    plugins:
      - *cache

  - label: ':rocket: Build'
    key: 'build'
    depends_on: 'install'
    commands:
      - pnpm build
    agents:
      queue: default
    plugins:
      - *cache

  - label: ':white_check_mark: Unit Tests'
    key: 'unit-tests'
    depends_on: 'build'
    commands:
      - pnpm test
    agents:
      queue: default
    plugins:
      - *cache

  - label: ':mag: E2E Tests'
    key: 'e2e-tests'
    depends_on: 'build'
    commands:
      - pnpm test-e2e
    agents:
      queue: default
    plugins:
      - *cache

  - label: ':book: Storybook Tests'
    key: 'storybook-tests'
    depends_on: 'build'
    commands:
      - pnpm test-storybook-ci
    agents:
      queue: default
    plugins:
      - *cache

  - label: ':chart_with_upwards_trend: Coverage Reports'
    depends_on:
      - 'unit-tests'
      - 'e2e-tests'
      - 'storybook-tests'
    commands:
      - pnpm coverage-report-create
    agents:
      queue: default
    artifact_paths:
      - coverage/
    plugins:
      - cache#v0.6.0:
          manifest: pnpm-lock.yaml
          path: node_modules
          restore: file
          save: pipeline
