import type { Metadata } from 'next';
import { currentLocale } from 'next-i18n-router';
import { Roboto } from 'next/font/google';

const font = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  params.locale = currentLocale();
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
